### ISSUE TITLE
Syntax question

### ISSUE THREAD

**Issue by Arehian** [hmi-utwente/Flipper-2.0#13]
Hi, I'm currently working on a project that uses ARIA VALUSPA as a foundation, which includes Flipper. Having looked at the xml files with the agent's templates, I noticed that some of the syntax within the templates are inconsistent, and I am unsure of the reason for this. In some templates, the preconditions are written in the following format:

`<condition><![CDATA[!is.dialogue.greeted.agent]]></condition>
`
Though in other areas it has been written as:

`<condition>is.dialogue.greeted.agent</condition>`

My understanding of CDATA is that it is to prevent a string from being interpreted as XML markup, though I am uncertain of the reason for its inconsistency in the code. Could somebody please clarify if this was likely just an oversight or if there is an additional reason?

Secondly, I am unsure of the use of DMImpBegin and DMImpEnd, as I have read somewhere that their use is to create a pause in a sentence, though I have seen them placed in sentences in what I would consider irregular locations for pauses, I'd appreciate if somebody could give an in-sentence example of exactly how they would each be used?

Thank you.

**Comment by Barachia** [comment]
Hi Arehian,

Sorry for not getting back earlier to your post.

You are right in that we use the CDATA for preventing XML markup. This is required whenever we want to use '<' or '>' for conditions that require greater than or lesser than. For readability, sometimes the CDATA is left out if there is no XML markup in there. I have to admit, it's inconsistent, and I think nowadays, most of us use CDATA regardless of its necessity in the templates.

For your second question, we intended the use of DMImpBegin and DMImpEnd as markers (Imp-tags) for emphasis in utterances, such that the agent would use a different gesture or emotion in between or perhaps change pitch or raise voice. Here's an example of using them:

Within Flipper:
```
<template id="assure_correct" name="reassure you heard correct">
 <preconditions>
  <condition><![CDATA[is.dialogue.response.text !== ""]]></condition>
  <condition><![CDATA[is.dialogue.response.confidence < 0.6]]</condition>
 </preconditions>
 <effects>
  <assign is="is.states.agent.fml.template">"inform_statement_y_02"</assign> 
  <assign is="is.states.agent.fml.parameters['var.var1']">"<![CDATA[Are you <tm id=\"DMImpBegin\"/> really sure <tm id=\"DMImpEnd\"/> about that?]]>"</assign>
  <assign is="is.states.agent.fml.parameters['emotion.em2.type']">"surprise"</assign>			
 </effects>
</template>
```
In this case, a random 'talking' gesture is generated for everything outside of the Imp-tags, and the surprise is expressed between the Imp-tags.

The corresponding FML template:
```
<?xml version="1.0" encoding="UTF-8"?>
<fml-apml composition="replace" reaction_type="none" reaction_duration="none" social_attitude="neutral">
 <aria-header purpose="inform-statement" />
  <bml>
   <speech id="s1" start="0.0" language="english" text="" voice="cereproc">
    <description level="1" type="gretabml">
     <reference>tmp/from-fml-apml.pho</reference>
    </description>			
    <tm id="DMBegin"/>
    <voice emotion='none'><aria-var id="var1" type="sentence"/></voice>
    <tm id="DMEnd"/>			
    <pitchaccent id="pa1" start="s1:DMImpBegin" level="none" end="s1:DMImpEnd" type="Hstar" importance="1"/>
    <boundary id="b1" start="s1:DMEnd-0.2" type="HH"/>
   </speech>
  </bml>	
  <fml>
   <emotion id="em1" type="neutral" regulation="felt" start="s1:DMBegin" end="s1:DMEnd" intensity="1" importance="1.0"/>
   <emotion id="em2" type="neutral" regulation="felt" start="s1:DMImpBegin" end="s1:DMImpEnd" intensity="1" importance="1.0"/>
   <certainty id="cr1" type="none" start="s1:DMBegin" end="s1:DMEnd" intensity="0.5" importance="0.5"/>
   <performative id="p1" type="inform" start="s1:DMImpBegin" end="s1:DMImpEnd" importance="1.0" />
  </fml>	
</fml-apml>
```

**Comment by Arehian** [comment]
Thank you for responding.

Ok, this really clears some things up, though I do now have more questions if you're willing to answer.

Firstly, if I have this right, the agent templates IDs are meant to match with the user input 'questions' names.

For example:

`<answer type="certain">socialobligations_greeting_wellbeing</answer>`

Matches with:

`<template id="socialobligations_greeting_wellbeing" name="Return wellbeing" conditional="true">`

So I can see that the user's voice input could be recognised as this "greeting_wellbeing" question, and met with the respective template, but I was wondering if it was possible to have multiple templates that respond to the same user input question (having each template require different conditions to be met).

For example, if the user were to say "I don't know", the response from the agent might be different depending on the context, is there an easy way to do this, or will I need to just create multiple user questions that are identical but will be used to activate different templates?


Secondly, I'm looking for a way to place a variable within a sentence spoken by the agent, does flipper have something to support this?

For example: The agent might say "Oh, well tell me more about your [variable]", with perhaps a function to set this variable prior to the template being used.

Thanks again.

**Comment by Barachia** [comment]
Yes, the ID matches up. If you look at the file `NLU.xml`, this one contains the template with id `MoveSelecter`, which takes the head of all the question-answer pairs. It will then call the template (the `checktemplates` part with regex) with the id of that move, which is in your example `social_obligations_greeting_wellbeing`.

Unlike the ID might suggest, this does **not** need to be unique. If you want to have different type of responses, it's possible to have templates with the same ID. Look at the template file `Moves_Eval_Quest1.xml`, which we used for the ARIA evaluation. Here we have different responses to the user's utterance, depending on the trust level, so for example the template there with ID `social_introduction_returnname`, there's two of those. A more clean way would be to use different ID's and then use a regex that for example checks `social_introduction_returnname.*` to check all templates with that specific prefix. Then in the conditions of those templates you could set the different conditions. In your case for the 'I don't know', you could make one template where the agent might want to rephrase and one where he might want to talk about something else.

To answer your second questions. Yes, in ARIA we used middleware to almost directly put the sensory input (which came from SSI) in the information state, which keeps track of all information in the dialogue. In the file `ARIA.xml` you can see the template with ID `20` and name `UserInput` which did just that. This templates retrieves new sensor messages and puts them in the information state and includes also the effect of setting the user text in another part of the information state. It's good practice to save all messages in the information state and if you want to use this information, assign it to a different part of the information state, which we did by putting it in the `is.states.user.move.text` part. Then the templates in `NLU.xml` where called whenever new text was added there and a response was retrieved from the question-answer database.

The final question you have involves the way we use FML (Functional Markup Language) in the ARIA-system. To give a brief introduction, how we generate behaviours with embodied conversational agents, such that we first retrieve the content (what do we want to say), we then create the FML in Flipper which you can see by all the assigns for `is.states.agent.fml`. This contains how we intent to say it. And then when the FML is sent to a behaviour realizer of an agent, this is translated in actual behaviour. 

`inform_statement_y_02` is the most commonly used in ARIA, because it's basically a template for just passing an utterance, with optional important emphasis (expressed in emotions). Anything that is just on the content level would use this FML template. In ARIA you did need to specify an FML template for every speech and/or behaviour you want to send.

I'm not sure what you mean by changing the full context of the conversation. Do you mean just talking about something else than Alice? Then yes, you need to define the FML template every time. You could perhaps make a smarter approach with one template that contains conditions for when to assign which FML template, such that you only need to fill in the parameters for all speech-containing templates, but this is no trivial task.

I hope this helps!

**Comment by Barachia** [comment]
Closing this, as the questions have been answered.
